### ISSUE TITLE
Feature Request: Smooth horizontal scrolling.

### ISSUE THREAD

**Issue by ItzDaWolfie** [HielkeMinecraft/OpenNoteBlockStudio#16]
making the memes is hard without a good look of what you've accomplished.

the scrolling scrolls about 1 whole "workspace" screen. i want it to do it a lil smoother m9
at least add a scrolling setting thing for us pl0x

**Comment by ShinkoNet** [comment]
Change page-by-page to tick-by tick in the settings.
![Minecraft_Note_Block_Studio_eCW81bwrC2](https://user-images.githubusercontent.com/10773386/58713974-1563a480-8407-11e9-8c3c-821103fe263b.png)
I've also proposed the marker to scroll at 60FPS instead of 30, which should make the marker look smoother when traversing the timeline.

**Comment by Benzeel** [comment]
I think they mean when it goes to the next tick it doesn't clip to it.

**Comment by ShinkoNet** [comment]
Since the way scrolling is implemented is via shifting the visible cells/rows on the screen, instead of moving smoothly through a list, it won't be done. Would take a ton of rewriting.
