### ISSUE TITLE
Unable to import a MIDI that too long

### ISSUE THREAD

**Issue by chenxi050402** [HielkeMinecraft/OpenNoteBlockStudio#163]
**Describe the bug**
Unable to load long MIDI files

**To Reproduce**
Import a very long MIDI file such as the UNDERTALE complete OST

**Expected behavior**
Lag a bit but able to load the song

**errorMessage**
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_controller:

Array index must be < 32000
at gml_Script_import_midi
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_import_midi (line -1)
gml_Script_draw_window_midi_import
gml_Script_draw_windows
gml_Script_control_draw
gml_Object_obj_controller_Draw_0

**Comment by TheAlienDrew** [comment]
I agree this is such an edge case... Additionally though, can't you split up large MIDI files into more than one array?

**Comment by Bentroen** [comment]
It should be possible in theory, but again, due to GameMaker's limitations, the notes aren't stored in a single array — rather, there's an entire array for every property of the note blocks (key, instrument, velocity, panning and pitch).

Let's say we duplicate all those arrays. Now every single operation involving note blocks is exponentially more complicated. How do you check the song length, iterate both arrays at once, or figure out in which array the blocks have to be in when you move them past the limit of the first one?

Not only that's an unreasonable amount of work, it would only mitigate the problem — it would double the maximum length of a song, and then at tick 64,000 there's the crash again.

Although it can't be fixed in the GameMaker version, I'll reopen it and add it to the v4.0 milestone, since it will no longer be an issue on the rewrite.

**Comment by chenxi050402** [comment]
It's fixed in 3.8.1.
