### ISSUE TITLE
1.16.1

### ISSUE THREAD

**Issue by Jaruto** [HielkeMinecraft/OpenNoteBlockStudio#176]
Its doesn't work on 1.16.1

1 make a song
2 save as schem
3 put into a 1.16.1 server/world
4 fail in making the song u wanted

I thought it would work

followed a youtube tuorital for it... doesn't work

**Comment by Bentroen** [comment]
As stated in the program, schematics are only compatible with versions up to 1.12, due to major changes to the world format that happened in 1.13. This will require a full rewrite of the schematic export feature, which we aim to provide in version 4.0 that's to be released later this year.

For now you can use a workaround to get schematics into newer versions: create a world in 1.12, load the schematic with MCEdit or your preferred tool, then load the world in 1.16.1. All instruments, including the ones added in 1.14, will be preserved.
