### ISSUE TITLE
Error when opening

### ISSUE THREAD

**Issue by xdTAGCLAN** [HielkeMinecraft/OpenNoteBlockStudio#183]
**Describe the bug**
I got an error message when opening the program after i just installed it. The message says:
---------------------------
Unsaved song - Minecraft Note Block Studio
---------------------------
Win32 function failed: HRESULT: 0x8876017c

Call:  at line 2202 in file \Graphics_DisplayM.cpp
---------------------------

**Expected behavior**
The program to just normally open.

**Additional context**

**Comment by xdTAGCLAN** [comment]
uhhh the message is wierd here it is again.

---------------------------
Unsaved song - Minecraft Note Block Studio
---------------------------
Win32 function failed: HRESULT: 0x8876017c

Call:  at line 2202 in file \Graphics_DisplayM.cpp
---------------------------

**Comment by xdTAGCLAN** [comment]
Heres the error again:

Unsaved song - Minecraft Note Block Studio

Win32 function failed: HRESULT: 0x8876017c

Call:  at line 2202 in file \Graphics_DisplayM.cpp

**Comment by Bentroen** [comment]
I've never seen this issue before, it's a crash happening at a very low level and most likely an issue with your computer rather than with the program's code. I need you to provide some information in order to figure out what's causing it:
- What's your operating system?
- What version of NBS are you using?
- Have you been able to run any other versions successfully on the same machine?
- How old is your graphics card?

Also, try the following:
- Reinstall NBS
- Make sure your graphics drivers are up to date
- Make sure your graphics card is DirectX 11-compatible
- If you have another machine, try running it there and see if you get the same error

**Comment by xdTAGCLAN** [comment]
Thanks! Updating my drivers worked!
