### ISSUE TITLE
Press option for default instruments isn't saved to preferences

### ISSUE THREAD

**Issue by CubixL** [HielkeMinecraft/OpenNoteBlockStudio#195]
**Describe the bug**
Certain options do not save when exiting ONBS. These include:

- Preferences/General: The auto-saving interval, five minutes by default (not the option itself, but the rate at which it autosaves)
- Settings/Instrument/Instrument settings: The "press" option that determines if the keys are pressed down when playing the song (only harp is set to "yes" by default)

**To Reproduce**
1. Change any of the settings above
2. Quit ONBS (save if you want)
3. Reopen it
4. The settings reverted back to default

**Expected behavior**
The preferences to save

**Additional context**
Some other options (remapping the piano keys, enabling the sound counter) didn't save for me before, but it was probably my fault for redownloading the software because of... stuff, and it looks like it saves now.

**Comment by Bentroen** [comment]
The auto-save interval saves and loads fine for me. Have you had a crash or closed the program in an unexpected way? The settings are only saved when you exit the program normally (i.e. by clicking the 'Close' button or the 'Exit' option in the File menu). This is a separate issue that could be patched sometime.
(BTW, the default interval is 10 minutes, not 5. Maybe you got something mixed up...?)

Press option: You're correct, those aren't saved anywhere, likely because the instrument settings are more of a thing to be set per song rather than for the whole program (custom instruments are saved per song, for instance). Since it'd be overkill to add 16 fields to every song holding those values, I'm fine with saving it alongside with the preferences.

I'll change this ticket to being about the latter issue.
