### ISSUE TITLE
[CRITICAL] Lost a song file because NBS asked me to recover and save another song

### ISSUE THREAD

**Issue by An-AURORE** [HielkeMinecraft/OpenNoteBlockStudio#196]
I have lost a song file while I was trying to export my songs to mp3. One of my songs (I'll call this song 1) I was trying to export first, which I did successfully. However, when I clicked on my other song (song 2), It asked me to recover the file for song 1, which replaced song 2. It then asked me to save the file for song 2, which I did because I didn't know what was happening. I lost all the information from song 2 as it became a duplicate of song 1. I also deleted song 2's file as I couldn't find a way to recover older versions of the file.

I do not know how or why it asked me to recover the song file, but what I did was:
- export song file 1 to mp3,
- heard a minor error in the timing of the song as **the tempo is slower at the start and speeds up to the tick speed displayed** (might be its own issue)
- tweaked the song and saved it
- exported song 1 again (it also popped up that it did it successfully)
- opened song 2
- asked me to recover song 1 etc.
I do not understand why it asked me to recover the song, as the asterisk (*) was absent from the song title.

I know that my song is lost completely at this point now, but I'd like to suggest the ability to view old iterations of the saved song so that I can recover songs in case it happens again.

**Comment by Bentroen** [comment]
> I do not know how or why it asked me to recover the song file

So, the explanation for this is that, every once in a while, the auto-recovery mechanic saves a copy of your current song to a backup file within the program data, then deletes this file when you exit the program (_normally_). When you **don't** exit normally, e.g. due to a crash, this file will not be deleted and its presence will be detected the next time you open the program, asking you to recover it.

With that clarified, it's now obvious that this mechanic is completely flawed, since if you have two songs open at the same time, they will write to the same backup location and one song will overwrite the other as soon as you open the second one. _\*facepalm\*_

I was investigating this issue for a long while, but it never became clear to me _how_ NBS was overwriting your files — it's never _supposed_ to write to any location, **unless** you ask it to do so. I was right with that thought, and your report made it crystal clear why: the pop-up asking if you want to save the song misleads you into saving it, however, since you just "recovered" the song that was open in the first window, the contents of the second file will be replaced with that as soon as you click 'Yes'.

I know it's really ironic that a feature that's designed to prevent you from losing work, has had exactly the opposite effect. I'm really sorry for the inconvenience; I know how awful it is to lose hours of hard work. Thanks a lot for reporting this issue, I'll get into fixing it right away :)

**Comment by An-AURORE** [comment]
> So, the explanation for this is that, every once in a while, the auto-recovery mechanic saves a copy of your current song to a backup file within the program data, then deletes this file when you exit the program (_normally_). When you **don't** exit normally, e.g. due to a crash, this file will not be deleted and its presence will be detected the next time you open the program, asking you to recover it.

Oh. That's why it asked my that specific time, as I would usually work on one song at a time. Today was the only case I'd multitask on multiple songs to export them to mp3.
With that being said, I do not use auto-recovery on any application to be fair, as I would **_manually_** press the save button as I progress through sections of the song, even pressing it for minor adjustments for notes. I'd like to know _if and where_ I can disable the feature: and no rush if you plan to add it.

**Comment by Bentroen** [comment]
Auto-recovery was disabled temporarily in 3.8.1 to prevent this issue. Songs are still saved to the backup location, but NBS will no longer ask you to recover them when it finds one.

The auto-recovery system will be reworked in the future to account for multiple instances and avoid overlaps like this.
