### ISSUE TITLE
Bad MIDI conversion (v3.3.8)

### ISSUE THREAD

**Issue by enderGuardian46** [HielkeMinecraft/OpenNoteBlockStudio#20]
In an older version I converted a MIDI containing Cipher by Kevin MacLeod and it sounded somewhat good. After updating to 3.8.8 I converted it again because Minecraft got new noteblock sounds but this time it sounded completely awfull.
Here is what it looked before: http://www.mediafire.com/file/6eft5w281nu2u70/Cipher.nbs/file
And here is what it looks like now: http://www.mediafire.com/file/btl0c0qxeqj2rcb/Bad_Cipher.nbs/file
And this is the MIDI I used: http://www.mediafire.com/file/ldmfa7l820llk78/Cipher.mid/file

The version I used before is the one that is still on the Stuff By David website.

**Comment by HielkeMinecraft** [comment]
Yeah because of the new instruments, some MIDI to instrument conversions were changed to better match the new note block sounds. I'll change this one back.

**Comment by ShinkoNet** [comment]
There is still an issue where if the same note is repeated twice for the same instrument (which often happens when two different channels get converted to the same noteblock instrument), the duplicate note is deleted. This can be bothersome when manually correcting the file as there has been note data that was destroyed in the process of conversion.

To fix this issue, delete lines 119-130 in import_midi.gml

I've had midi imported this way for ages and it is a lot easier to work with when note data is intact.
