### ISSUE TITLE
Change BPM

### ISSUE THREAD

**Issue by lemonztries-user** [HielkeMinecraft/OpenNoteBlockStudio#202]
Hello everyone, maybe you already asked questions on a similar topic, if there is a way to control the BPM speed by changing the tickrate without plugins and mods? [schematics]

I know there is a TickrateChanger mod, it works great, but this mod is supported up to version 1.12.2

Tried it via / gamerule randomTickSpeed ​​but it doesn't seem to be the same at all who ran into it,
how did you solve the problem?

**Comment by Bentroen** [comment]
This is already possible with data packs. Since you asked specifically for schematics, sadly, it doesn't support custom tempos yet. TickrateChanger is one of the few workarounds you can use, which isn't that bad since schematics only support 1.12.2 anyway (you'll just not be able to use the instruments from 1.14+).

Also, the `randomTickSpeed` gamerule only changes the rate at which random game events occur (i.e. plants growing), it doesn't affect the game's speed itself.

We plan to allow any tempo on schematics in the future by clipping notes to the nearest tick when they don't match 10 or 20 t/s. :)

**Comment by lemonztries-user** [comment]
> This is already possible with data packs. Since you asked specifically for schematics, sadly, it doesn't support custom tempos yet. TickrateChanger is one of the few workarounds you can use, which isn't that bad since schematics only support 1.12.2 anyway (you'll just not be able to use the instruments from 1.14+).
> 
> Also, the `randomTickSpeed` gamerule only changes the rate at which random game events occur (i.e. plants growing), it doesn't affect the game's speed itself.
> 
> We plan to allow any tempo on schematics in the future by clipping notes to the nearest tick when they don't match 10 or 20 t/s. :)

Спасибо за ответ!
