### ISSUE TITLE
Number of lines

### ISSUE THREAD

**Issue by lemonztries** [HielkeMinecraft/OpenNoteBlockStudio#206]
Hello, can you find out how many lines can be played at the same time without offsets?

At my peak, it can reach up to 9 lines and offsets begin and everything turns into a mess

According to the idea, the same should not be, since new levels are added?

![image](https://user-images.githubusercontent.com/71596737/96331405-89870280-1065-11eb-9640-999624820eca.png)

**Comment by Bentroen** [comment]
Yes, there's currently an issue with schematic layers being out of sync (described in #105). I have no clue from how many layers it starts to happen -- it would require further investigation, but since we're due to redesigning the whole schematic layout, as the current one is seriously outdated, it's not really worth fixing it at the moment. Sorry for the inconvenience!
