### ISSUE TITLE
A lot of lag when using the program

### ISSUE THREAD

**Issue by apollux95** [HielkeMinecraft/OpenNoteBlockStudio#211]
Whenever I'm using the program, everything is very laggy and it takes a long time to respond even when it's the only program that's open.

**Comment by Bentroen** [comment]
In order to figure out the cause of the issue, we'll need additional details. What are your computer specs and screen resolution? How high is your CPU usage in Task Manager while using the program? Are your graphics drivers up to date? And finally, are you doing any performance-intensive tasks, like playing many notes at the same time?

If your computer was made in the last 5 years, there's a good chance NBS will be able to play at least a basic song in it without bogging down. If anything, I'd suggest you to lower your screen resolution/decrease the size of the program's window, as that will decrease the number of things it has to draw on the screen. If you have a dedicated graphics card, also make sure to set NBS to use it (e.g. for NVIDIA GPUs you do that on the NVIDIA Control Panel).

**Comment by apollux95** [comment]
I have a pretty mid-end PC with a 4 core AMD A8-9600 processor with a CPU usage of about 90% while using the program. My motherboard is a MSI B350M-PRO VDH with 8GB of RAM installed. Graphics card is a NVIDIA GT 730 with 4GB of Video RAM and a slightly outdated driver. And finally, No. Even with only a few notes in (sometimes none at all,) the program is still very laggy.

I got this PC on September last year. Also, thanks for the tips, I'll try using them later and see if they make a difference.

**Comment by Bentroen** [comment]
Hmm yeah, your specs are definitely not the problem (they're better than the laptop I do most of the development on, and it runs just fine there). The 90% CPU usage is a big hint though. Does all of it come from NBS? Perhaps there's something running in the background that's stealing resources and causing it to lag.

**Comment by apollux95** [comment]
I think the cause for the high CPU usage is my antivirus software, Steam, and Twitch running in the background.
