### ISSUE TITLE
Exprience lags when playing

### ISSUE THREAD

**Issue by chenxi050402** [HielkeMinecraft/OpenNoteBlockStudio#222]
**Describe the bug**
I experience lags in version 3.8.1 and higher CPU usage

**Expected behavior**
CPU usage same as 3.8.0

**Screenshots**
![image](https://user-images.githubusercontent.com/62318879/103472737-daff7d80-4d88-11eb-9f5d-5488e60abbf5.png)
Opening the same file, window size 640x480

**Comment by chenxi050402** [comment]
Persists in 3.8.2

**Comment by Bentroen** [comment]
Hey, can you tell me what you were doing/what was displayed on screen when you noticed the higher CPU usage? Or does it happen all the time?

**Comment by chenxi050402** [comment]
> Hey, could you tell me what you were doing/what was displayed on screen when you noticed the higher CPU usage? Or does it happen all the time?

It's all the time, even with a blank file.

**Comment by Bentroen** [comment]
Hello! Could you confirm if the issue persists?

If you noticed this while something was being displayed on the screen, we could trace it back to something we added that may be causing the higher CPU usage. Since it seems to happen all the time, sadly there's not much we can do about it!

Although, 4% seems to me like a normal CPU usage for NBS being idle.

**Comment by chenxi050402** [comment]
The CPU usage is still there but no noticeable lags when playing. This is on a Core i9 10900k and it takes about 10% on a Core 15 1035G7, all at the default windowed resolution.

**Comment by Bentroen** [comment]
The reason for the high CPU usage, even when NBS is seemingly idle, is that everything must be drawn to the screen every frame in order to appear on screen, due to the way GameMaker works (even the stuff that's not moving/changing). This causes a lot of unnecessary CPU usage. As GameMaker was never intended to make GUI applications, the only solution would be to move to a proper GUI engine, which we're currently working on. I'm sorry for the inconvenience though!

I'll close the issue, but feel free to add any other detail in a comment. :)
