### ISSUE TITLE
[Feature Request] Adding .schem files as possible export option.

### ISSUE THREAD

**Issue by Dago-Duck** [HielkeMinecraft/OpenNoteBlockStudio#231]
**Is your feature request related to a problem? Please describe.**
Open Note Block Studio is a great program, and I've only just discovered it. Sadly, when trying to export my project, in which I've used lots of 1.13+ sounds, there was no option for exporting as a .schem file. I've then searched the internet for help. (Using .schematic files in 1.13+ --> All sounds are the harp; converting .schematic files to .schem files --> Seems to not be possible at all; and the last thing I did was paste the schematic in a 1.12 world, and then update the world to 1.16 --> pumpkins have to be replaced by hand, because in 1.12 they are pasted as default pumpkins, which turned to carved_pumpkins in 1.14.)

**Describe the enhancement you'd like**
In order to support the new 1.13+ sounds it would be really nice to be able to export a schematic to a .schem file as well.
I've got no idea how long it would take to develop, but it would be a nice addition! Thanks for reading!

**Comment by Bentroen** [comment]
Hello! Thank you for reporting the issue. We are aware of it and it's on our list of things to implement. However, it is kind of a tricky one since not only the `.schem` file specification is completely different from `.schematic`s, we must also redesign the whole structure to overcome the fact that 1) we plan to allow any tick rate to be exported by quantizing them to 20 t/s and using odd-tick pulses, and 2) since 1.14, sand is the only block that makes a snare sound, and it falls everywhere across the structure.

Additionally, the reason why all sounds change to harp in newer versions is that the way note blocks are stored changed completely in 1.13, and the old `.schematics` lack the necessary data to tell Minecraft what instrument to use. However, it's possible to import structures in 1.13+ worlds if you first **load them in a 1.12 world, then convert the world to a newer version.**

We're already tracking this issue in #29, so I'll close this one as a duplicate. Feel free to comment there if you have any suggestions. :)
