### ISSUE TITLE
[Feature Request]Can NBS make multilingual？

### ISSUE THREAD

**Issue by jjcyf** [HielkeMinecraft/OpenNoteBlockStudio#233]
**Is your feature request related to a problem? Please describe.**
It is difficult for people in my country to fully understand English.
**Describe the enhancement you'd like**
I hope NBS can add multi language settings, or can I add them myself?

**Comment by Bentroen** [comment]
Hello! Translations are definitely on our list of things to implement, however, as we're in the process of rewriting the whole program in another engine, we'll likely leave it for version 4.0, since it's kinda difficult to implement in the current versions.

This has been requested in issue #112, you can follow that issue for updates on translations :)
