### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by Pajsen9263** [HielkeMinecraft/OpenNoteBlockStudio#245]
Will MacOS support ever come? I can't compile for MacOS.

**Comment by Speeder323** [comment]
There is an answer in the FAQ channel on the discord server, but to be short: 
There is no MacOS/Linux version due to ONBS using some windows-only libraries. 
Bentroen hopes to fix it in v4.0 (The Python Rewrite), but for now the only solution would be WINE, however using it would be a bit "at your own risk" because it doesn't always work, if at all.

Issue on Mac/Linux support: #4

**Comment by Bentroen** [comment]
Closing as duplicate, as per above.
