### ISSUE TITLE
Feature: Option to choose priority

### ISSUE THREAD

**Issue by Edude42** [HielkeMinecraft/OpenNoteBlockStudio#48]
It'd be neat to add an optional box in the Preferences to choose what processor priority to run on to reduce slowdowns. (If the program is running as admin)

**Comment by ShinkoNet** [comment]
Another way to reduce slowdown is to expand the entire note block song (select all, expand selection) then double the tickrate. With an upcoming version we can disable the fading animations to enhance performance too.

I think since this is done through task manager, and we don't want to mess with the system itself too much (this is gamemaker code after all) I doubt we will implement this.

**Comment by HielkeMinecraft** [comment]
Yeah this feature is too technical, And this is already possible with task manager.
